# Generated by Django 5.0.1 on 2025-08-07 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('journal_type', models.CharField(choices=[('sales', 'Journal des ventes'), ('purchases', 'Journal des achats'), ('cash', 'Journal de caisse'), ('bank', 'Journal de banque'), ('general', 'Journal général'), ('opening', "Journal d'ouverture"), ('closing', 'Journal de clôture')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=20)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_balanced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.accountingjournal')),
            ],
            options={
                'unique_together': {('journal', 'entry_number')},
            },
        ),
        migrations.CreateModel(
            name='BelgianChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('1', "Fonds propres, provisions et dettes à plus d'un an"), ('2', "Frais d'établissement, actifs immobilisés et créances à plus d'un an"), ('3', "Stock et commandes en cours d'exécution"), ('4', 'Créances et dettes à un an au plus'), ('5', 'Placements de trésorerie et valeurs disponibles'), ('6', 'Charges'), ('7', 'Produits')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.belgianchartofaccounts')),
            ],
            options={
                'ordering': ['account_number'],
            },
        ),
        migrations.CreateModel(
            name='AccountingEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_code', models.CharField(blank=True, max_length=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='admin_dashboard.accountingentry')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.belgianchartofaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='BelgianVATDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('period', models.PositiveIntegerField()),
                ('grid_00_operations_exempted', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grid_01_operations_6_percent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grid_02_operations_12_percent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grid_03_operations_21_percent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grid_54_vat_6_percent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grid_55_vat_12_percent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grid_56_vat_21_percent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grid_59_vat_deductible', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grid_71_vat_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grid_72_vat_to_recover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('period_type', 'year', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contractor', 'Contractuel'), ('intern', 'Stagiaire')], max_length=20)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('national_number', models.CharField(max_length=11, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_type', models.CharField(choices=[('sale', 'Facture de vente'), ('purchase', "Facture d'achat"), ('credit_note', 'Note de crédit')], max_length=20)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('subtotal_excl_vat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_incl_vat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('billing_address', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard.accountingentry')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_excl_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_excl_vat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_incl_vat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='admin_dashboard.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Congés payés'), ('sick', 'Congé maladie'), ('maternity', 'Congé maternité'), ('paternity', 'Congé paternité'), ('unpaid', 'Congé sans solde')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('card', 'Carte bancaire'), ('check', 'Chèque'), ('stripe', 'Stripe')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admin_dashboard.invoice')),
            ],
        ),
    ]
