# Generated by Django 5.0.1 on 2025-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='iban',
            field=models.CharField(blank=True, help_text='Numéro IBAN', max_length=34),
        ),
    ]
